---
fontsize: 9pt
mainfont: Helvetica
format: pdf
---

```{r setup, echo = FALSE, message = FALSE}
library(ganttrify)
library(readr)
library(here)
```

```{r, echo = FALSE, include = TRUE, fig.width = 12, fig.height = 16}
#| label: fig-gantt
#| fig-cap: "Key stages and milestones for the SSI 2025 grant project. Timings of the different work packages (by colour) are shown as horizontal lines across the 24-month project timeline. Milestones are indicated as letters: S = Software release, P = Paper submission, T = Training material publication, W = Scientific workshop"
#| cache: false
#| fig-format: png
#| fig-dpi: 300
#| dev: "png"
plan <- read_csv(here("gantt", "plan.csv"), show_col_types = FALSE)
milestones <- read_csv(here("gantt", "milestones.csv"), show_col_types = FALSE)

ganttrify(
    project = plan,
    spots = milestones,
    project_start_date = "2026-01",
    font_family = "Helvetica",
    month_breaks = 3,
    size_text_relative = 1.4,
    colour_palette = c("#1f77b4", "#ff7f0e", "#2ca02c", "#d62728", "#9467bd"),
    alpha_wp = 0.9,
    line_end = "round"
)
```